import { ArrowRight, CheckCircle2, ChevronRight, LockKeyhole, Sparkles } from "lucide-react";
import { Link } from "react-router-dom";
import { PageFrame, PageIntro, ModuleProgress } from "@/components/AppShell";
import { modules } from "@/data/content";
import { useSession } from "@/lib/learningSession";

export default function Learn() {
  const { completedModules, profile } = useSession();
  return <PageFrame backTo="/" current={2} total={5}><PageIntro eyebrow="Langkah 2 · Jelajah" title={profile ? `Halo, ${profile.nickname}! Yuk pilih materi` : "Pilih materi yang ingin dipelajari"} description="Pilih satu kartu untuk belajar. Kamu bebas mulai dari mana saja, lalu coba simulasi di bagian akhir." current={2} total={5}><ModuleProgress /></PageIntro><div className="mb-6 flex items-center justify-between rounded-2xl border border-yellow-100 bg-yellow-50 px-4 py-3 text-sm text-yellow-900" data-testid="learn-tip-banner"><Sparkles className="size-5 shrink-0" /><p><strong>Tips:</strong> belajar sebentar tapi sering juga boleh.</p><Link to="/piringku" className="hidden font-extrabold text-yellow-800 sm:block" data-testid="learn-plate-shortcut">Coba piringku →</Link></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{modules.map((module) => { const done = completedModules.includes(module.id); return <Link to={`/materi/${module.id}`} key={module.id} className="group rounded-3xl border border-slate-100 bg-white p-5 shadow-[0_8px_30px_rgba(0,0,0,.04)] transition-all hover:-translate-y-1 hover:shadow-[0_14px_34px_rgba(0,0,0,.08)]" data-testid={`module-card-${module.id}`}><div className="flex items-start justify-between"><span className={`grid size-12 place-items-center rounded-2xl text-2xl ${module.accent === "pink" ? "bg-pink-100" : module.accent === "purple" ? "bg-purple-100" : module.accent === "yellow" ? "bg-yellow-100" : module.accent === "blue" ? "bg-sky-100" : "bg-emerald-100"}`}>{module.emoji}</span>{done ? <span className="flex items-center gap-1 rounded-full bg-emerald-50 px-2 py-1 text-xs font-extrabold text-emerald-700"><CheckCircle2 className="size-3" />Selesai</span> : <span className="text-xs font-extrabold text-slate-400">0{module.number}</span>}</div><p className="mt-5 text-xs font-extrabold uppercase tracking-[0.12em] text-pink-500">{module.category}</p><h2 className="mt-2 font-heading text-xl font-extrabold text-slate-800">{module.title}</h2><p className="mt-2 text-sm leading-relaxed text-slate-500">{module.summary}</p><div className="mt-5 flex items-center justify-between border-t border-slate-100 pt-4 text-sm font-extrabold text-pink-600"><span>{done ? "Buka lagi" : "Pelajari"}</span><ChevronRight className="size-4 transition-transform group-hover:translate-x-1" /></div></Link>})}</div><div className="mt-8 grid gap-4 md:grid-cols-3"><QuickLink to="/camilan" emoji="🍪" title="Switch camilan" text="Cari ide pengganti yang lebih beragam." /><QuickLink to="/skenario" emoji="💬" title="Coba skenario" text="Latih pilihan dalam situasi sehari-hari." /><QuickLink to="/higiene" emoji="🧼" title="Checklist higiene" text="Centang kebiasaan aman bersama." /></div></PageFrame>;
}

function QuickLink({ to, emoji, title, text }: { to: string; emoji: string; title: string; text: string }) { return <Link to={to} className="flex items-center gap-4 rounded-3xl border border-slate-100 bg-white p-4 shadow-sm transition hover:-translate-y-0.5" data-testid={`quick-link-${title.toLowerCase().replaceAll(" ", "-")}`}><span className="grid size-12 place-items-center rounded-2xl bg-pink-50 text-2xl">{emoji}</span><span className="min-w-0"><strong className="block font-heading text-base text-slate-800">{title}</strong><span className="block text-sm text-slate-500">{text}</span></span><ArrowRight className="ml-auto size-4 shrink-0 text-pink-500" /></Link> }