import { ArrowUpRight, BookOpen, ExternalLink, Info, ShieldAlert } from "lucide-react";
import { Link } from "react-router-dom";
import { PageFrame, PageIntro } from "@/components/AppShell";
import { akgMacroRows, akgMineralRows, akgReferenceRows, akgVitaminRows, references, type AkgNutrientRow } from "@/data/content";

const uploadedAkgPdf = "https://customer-assets-39nsmqrw.emergentagent.net/job_balita-belajar-gizi/artifacts/qqvff0mw_PMK_No__28_Th_2019_ttg_Angka_Kecukupan_Gizi_Yang_D_250421_155247.pdf";

export default function References() {
  return <PageFrame backTo="/ringkasan"><PageIntro eyebrow="Baca lebih lanjut" title="Referensi & Catatan Penting" description="Materi ini dibuat sebagai media edukasi interaktif dengan rujukan resmi. Untuk kondisi khusus, tetap utamakan konsultasi tenaga kesehatan." /><div className="grid min-w-0 gap-5 lg:grid-cols-1"><section className="min-w-0 space-y-4" data-testid="references-list">{references.map((reference, index) => <a key={reference.title} href={reference.url} target="_blank" rel="noreferrer" className="group block min-w-0 rounded-3xl border border-slate-100 bg-white p-5 shadow-[0_8px_30px_rgba(0,0,0,.04)] transition hover:-translate-y-1 hover:border-pink-200" data-testid={`reference-card-${index + 1}`}><div className="flex min-w-0 items-start gap-4"><span className="grid size-11 shrink-0 place-items-center rounded-2xl bg-pink-50 text-pink-600"><BookOpen className="size-5" /></span><div className="min-w-0 flex-1"><div className="flex min-w-0 items-start justify-between gap-3"><h2 className="min-w-0 font-heading text-lg font-extrabold text-slate-800">{reference.title}</h2><ArrowUpRight className="size-4 shrink-0 text-slate-400 transition group-hover:-translate-y-0.5 group-hover:translate-x-0.5 group-hover:text-pink-500" /></div><p className="mt-2 text-sm text-slate-500">{reference.institution} · {reference.year}</p><p className="mt-3 truncate text-xs font-bold text-pink-600">{reference.url}</p></div></div></a>)}</section><aside className="grid min-w-0 gap-5 lg:grid-cols-[minmax(0,1.25fr)_minmax(0,.75fr)]"><AkgReferenceCard /><div className="rounded-3xl border border-amber-100 bg-amber-50 p-6" data-testid="reference-disclaimer"><div className="flex items-center gap-2 text-amber-800"><ShieldAlert className="size-5" /><h2 className="font-heading text-lg font-extrabold">Disclaimer media edukasi</h2></div><p className="mt-3 text-sm leading-relaxed text-amber-950/80">Informasi pada website ini ditujukan sebagai media edukasi dan tidak menggantikan konsultasi dengan tenaga kesehatan. Jika anak memiliki kondisi kesehatan khusus, alergi, atau masalah makan, konsultasikan dengan tenaga kesehatan.</p></div></aside></div></PageFrame>;
}

function AkgReferenceCard() {
  return <section className="rounded-3xl border border-sky-100 bg-sky-50 p-5 sm:p-6" data-testid="reference-akg-card"><div className="flex items-center gap-2 text-sky-700"><Info className="size-5" /><h2 className="font-heading text-lg font-extrabold">Acuan AKG kelompok usia</h2></div><p className="mt-3 text-sm leading-relaxed text-slate-700">Ringkasan lengkap Tabel 1–3 Permenkes No. 28 Tahun 2019. Semua angka di bawah adalah acuan kelompok per orang per hari, bukan kebutuhan individual.</p><div className="mt-4 overflow-x-auto rounded-2xl bg-white"><table className="min-w-[620px] w-full text-left text-xs" data-testid="akg-table"><thead className="bg-sky-100 text-sky-900"><tr><th className="px-3 py-3 font-extrabold">Kelompok di website</th><th className="px-3 py-3 font-extrabold">Acuan PDF</th><th className="px-3 py-3 font-extrabold">Energi</th><th className="px-3 py-3 font-extrabold">Protein</th><th className="px-3 py-3 font-extrabold">Lemak</th><th className="px-3 py-3 font-extrabold">Karbohidrat</th></tr></thead><tbody className="divide-y divide-sky-50">{akgReferenceRows.map((row) => <tr key={row.websiteAge} data-testid={`akg-row-${row.websiteAge.replaceAll(" ", "-")}`}><td className="px-3 py-3 font-bold text-slate-700">{row.websiteAge}</td><td className="px-3 py-3 text-slate-500">{row.officialGroup}</td><td className="px-3 py-3 font-bold text-slate-700">{row.energy}</td><td className="px-3 py-3 font-bold text-slate-700">{row.protein}</td><td className="px-3 py-3 font-bold text-slate-700">{row.fat}</td><td className="px-3 py-3 font-bold text-slate-700">{row.carbohydrate}</td></tr>)}</tbody></table></div><p className="mt-3 text-xs leading-relaxed text-sky-900/70">Catatan: PDF menggunakan kelompok 1–3 tahun dan 4–6 tahun, sehingga label 12–23 bulan dan 4–5 tahun di website dipetakan ke acuan terdekatnya.</p><div className="mt-5 space-y-3"><AkgTableSection id="macro" title="Tabel 1 · Makro, serat, dan air" page="halaman 6–7" rows={akgMacroRows} /><AkgTableSection id="vitamin" title="Tabel 2 · Vitamin" page="halaman 9–11" rows={akgVitaminRows} /><AkgTableSection id="mineral" title="Tabel 3 · Mineral" page="halaman 12–14" rows={akgMineralRows} /></div><p className="mt-4 text-xs leading-relaxed text-sky-900/70">Satuan yang digunakan: RE = Retinol Equivalent, mcg = mikrogram, mg = miligram. Catatan kaki mengikuti dokumen sumber.</p><a href={uploadedAkgPdf} target="_blank" rel="noreferrer" className="mt-4 inline-flex font-bold text-sky-700 hover:text-sky-800" data-testid="uploaded-akg-pdf-link">Buka PDF Permenkes yang digunakan <ExternalLink className="ml-2 size-4" /></a><Link to="/mulai-profil" className="mt-3 flex font-bold text-sky-700 hover:text-sky-800" data-testid="reference-profile-link">Lihat kelompok usia <ExternalLink className="ml-2 size-4" /></Link></section>;
}

function AkgTableSection({ id, title, page, rows }: { id: string; title: string; page: string; rows: AkgNutrientRow[] }) {
  return <details open={id === "macro"} className="overflow-hidden rounded-2xl border border-sky-100 bg-white" data-testid={`akg-${id}-section`}><summary className="flex cursor-pointer list-none items-center justify-between gap-3 px-4 py-4 font-heading text-sm font-extrabold text-slate-800 marker:hidden"><span>{title}</span><span className="text-xs font-bold text-slate-400">{page} · buka/tutup</span></summary><div className="overflow-x-auto border-t border-sky-50"><table className="min-w-[560px] w-full text-left text-xs" data-testid={`akg-${id}-table`}><thead className="bg-[#f8fbff] text-sky-900"><tr><th className="px-3 py-3 font-extrabold">Zat gizi</th><th className="px-3 py-3 font-extrabold">Satuan</th><th className="px-3 py-3 font-extrabold">1–3 tahun</th><th className="px-3 py-3 font-extrabold">4–6 tahun</th></tr></thead><tbody className="divide-y divide-sky-50">{rows.map((row) => <tr key={row.name} data-testid={`akg-${id}-row-${row.name.toLowerCase().replaceAll(" ", "-")}`}><td className="px-3 py-2.5 font-bold text-slate-700">{row.name}</td><td className="px-3 py-2.5 text-slate-500">{row.unit}</td><td className="px-3 py-2.5 font-bold text-slate-700">{row.age13}</td><td className="px-3 py-2.5 font-bold text-slate-700">{row.age46}</td></tr>)}</tbody></table></div></details>;
}