import { useState } from "react";
import { CheckCircle2, MessageCircle, XCircle } from "lucide-react";
import { Link } from "react-router-dom";
import { PageFrame, PageIntro } from "@/components/AppShell";

const options = ["Melarang semua camilan secara langsung", "Membiarkan anak memilih semua makanan yang disukai", "Mengurangi secara bertahap dan menawarkan pilihan camilan yang lebih bergizi", "Tidak memberikan makanan sampai anak mau makan"];

export default function Scenario() {
  const [selected, setSelected] = useState<number | null>(null);
  return <PageFrame backTo="/kuis" nextTo="/higiene" nextLabel="Lanjut ke Higiene" current={5} total={5}><PageIntro eyebrow="Latihan keputusan" title="Yuk, Coba Tentukan Pilihanmu! 💬" description="Situasi sehari-hari tidak selalu mudah. Pilih respons yang paling membantu dan tetap hangat." /><div className="mx-auto max-w-3xl"><section className="rounded-[2rem] border border-purple-100 bg-purple-50 p-6 sm:p-8" data-testid="scenario-card"><div className="flex gap-4"><span className="grid size-12 shrink-0 place-items-center rounded-2xl bg-white text-purple-600 shadow-sm"><MessageCircle /></span><p className="text-lg font-extrabold leading-relaxed text-slate-800" data-testid="scenario-question">Anak lebih suka ngemil makanan ringan kemasan dan sering menolak makanan utama. Apa yang dapat dilakukan?</p></div><div className="mt-7 space-y-3">{options.map((option, index) => <button key={option} onClick={() => setSelected(index)} className={`flex min-h-14 w-full items-center gap-3 rounded-2xl border bg-white p-3 text-left text-sm font-bold transition ${selected === index ? "border-purple-400 bg-purple-100 ring-4 ring-purple-100" : "border-white hover:border-purple-200"}`} data-testid={`scenario-option-${index + 1}`}><span className="grid size-8 shrink-0 place-items-center rounded-xl bg-purple-100 text-xs font-extrabold text-purple-700">{String.fromCharCode(65 + index)}</span><span>{option}</span></button>)}</div>{selected !== null && <div className={`animate-soft-pop mt-6 rounded-3xl p-5 ${selected === 2 ? "bg-emerald-50" : "bg-yellow-50"}`} role="status" data-testid="scenario-feedback"><div className="flex gap-3">{selected === 2 ? <CheckCircle2 className="mt-0.5 size-5 shrink-0 text-emerald-600" /> : <XCircle className="mt-0.5 size-5 shrink-0 text-yellow-700" />}<div><h2 className="font-heading text-lg font-extrabold text-slate-800">{selected === 2 ? "Pilihan yang mendukung" : "Coba pertimbangkan lagi"}</h2><p className="mt-2 text-sm leading-relaxed text-slate-700">Pilihan yang paling membantu adalah <strong>C: mengurangi secara bertahap dan menawarkan pilihan camilan yang lebih bergizi</strong>. Dengan begitu, orang tua mengarahkan tanpa membuat anak merasa dihukum.</p></div></div></div>}</section><Link to="/higiene" className="mt-6 block rounded-3xl border border-pink-100 bg-white p-5 text-center font-extrabold text-pink-600 shadow-sm hover:bg-pink-50" data-testid="scenario-next-link">Lanjut cek kebiasaan higiene →</Link></div></PageFrame>;
}